class col():
    ESC = "\033["
    RES = RESET = ESC+"0m"
    
    #gamma/brightness
    G0 = GAM_0 = ESC+"2m"
    G1 = GAM_1 = ESC+"22m"
    G2 = GAM_2 = ESC+"1m"
    
    #foreground color
    FG_BLACK = ESC+"30m"
    FG_RED = ESC+"31m"
    FG_GREEN = ESC+"32m"
    FG_YELLOW = ESC+"33m"
    FG_BLUE = ESC+"34m"
    FG_MAGENTA = ESC+"35m"
    FG_CYAN = ESC+"36m"
    FG_WHITE = ESC+"37m"
    CFG_RESET = FG_RESET = ESC+"39m"

    #background color
    BG_BLACK = ESC+"40m"
    BG_RED = ESC+"41m"
    BG_GREEN = ESC+"42m"
    BG_YELLOW = ESC+"43m"
    BG_BLUE = ESC+"44m"
    BG_MAGENTA = ESC+"45m"
    BG_CYAN = ESC+"46m"
    BG_WHITE = ESC+"47m"
    CBG_RESET = BG_RESET = ESC+"49m"

    #clear functions
    CLR_RIGHT = ESC+"0K"
    CLR_LEFT = ESC+"1K"
    CLR_LINE = ESC+"2K"
    CLR_DOWN = ESC+"0J"
    CLR_UP = ESC+"1J"
    CLR_SCRN = ESC+"2J"

    #complex foreground color
    CF0 = CFG_BLACK =   ESC+"22;30m"
    CF4 = CFG_MAROON =  ESC+"22;31m"
    CF2 = CFG_GREEN =   ESC+"22;32m"
    CF6 = CFG_GOLD =    ESC+"22;33m"
    CF1 = CFG_NAVY =    ESC+"22;34m"
    CF5 = CFG_PURPLE =  ESC+"22;35m"
    CF3 = CFG_TEAL =    ESC+"22;36m"
    CF7 = CFG_SILVER =  ESC+"22;37m"
    CF8 = CFG_GRAY =    ESC+ "1;30m"
    CFC = CFG_RED =     ESC+ "1;31m"
    CFA = CFG_LIME =    ESC+ "1;32m"
    CFE = CFG_YELLOW =  ESC+ "1;33m"
    CF9 = CFG_BLUE =    ESC+ "1;34m"
    CFD = CFG_MAGENTA = ESC+ "1;35m"
    CFB = CFG_CYAN =    ESC+ "1;36m"
    CFF = CFG_WHITE =   ESC+ "1;37m"

    #complex background color
    CB0 = CBG_BLACK =   ESC+"22;40m"
    CB4 = CBG_MAROON =  ESC+"22;41m"
    CB2 = CBG_GREEN =   ESC+"22;42m"
    CB6 = CBG_GOLD =    ESC+"22;43m"
    CB1 = CBG_NAVY =    ESC+"22;44m"
    CB5 = CBG_PURPLE =  ESC+"22;45m"
    CB3 = CBG_TEAL =    ESC+"22;46m"
    CB7 = CBG_SILVER =  ESC+"22;47m"
    CB8 = CBG_GRAY =    ESC+ "1;40m"
    CBC = CBG_RED =     ESC+ "1;41m"
    CBA = CBG_LIME =    ESC+ "1;42m"
    CBE = CBG_YELLOW =  ESC+ "1;43m"
    CB9 = CBG_BLUE =    ESC+ "1;44m"
    CBD = CBG_MAGENTA = ESC+ "1;45m"
    CBB = CBG_CYAN =    ESC+ "1;46m"
    CBF = CBG_WHITE =   ESC+ "1;47m"
